export const skills = [
  { name: 'Custom Web Design', description: 'Tailored website designs that reflect your brand identity and meet your specific needs.', icon: 'palette', iconLibrary: 'lucide' },
  { name: 'Responsive Design', description: 'Websites that look great and function flawlessly on all devices, from desktops to smartphones.', icon: 'smartphone', iconLibrary: 'lucide' },
  { name: 'Maintenance & Support', description: 'Ongoing website maintenance and support to keep your site running smoothly and securely.', icon: 'wrench', iconLibrary: 'lucide' },
  { name: 'Domain & Hosting', description: 'Assistance with domain registration and reliable web hosting solutions for your website.', icon: 'server', iconLibrary: 'lucide' },
];

export const projects = [
  {
    name: 'AMOR WEDDINGS',
    description: "A business portfolio for a men's clothing brand. This website includes an advanced gallery",
    image: 'images/collage-amorweddings-3.png',
    live: 'https://amorweddings.onrender.com',
  },
  {
    name: 'Shazzz',
    description: 'A static personal portfolio website showcasing the experiences and establishments of Shazzz.',
    image: 'images/collage-shazzz-2.png',
    live: 'https://shazzz.onrender.com',
  },
  {
    name: 'Spicenza',
    description: 'A spices import & export company website design. This website includes an advanced dark-mode and light-mode option.',
    image: 'images/spicenza-2.png',
    live: 'https://spicenza.vercel.app',
  },
  {
    name: 'Artisan Creations',
    description: 'An art & craft business portfolio website design. This website includes images generated by AI.',
    image: 'images/artisancreations-2.png',
    live: 'https://artisancreations.vercel.app',
  },
  {
    name: 'MMKflix',
    description: 'A Netflix clone built with React and TMDB API integration.',
    image: 'images/collage-mmkflix-1.png',
    live: 'https://mmkflix.vercel.app',
  },
  {
    name: 'ToDo App',
    description: 'A modern todolist application.',
    image: 'images/screencapture-mmk-todoapp-vercel-app-2024-10-24-06_39_05.png',
    live: 'https://mmk-todoapp.vercel.app',
  },
  {
    name: 'Airbnb Clone',
    description: 'A full-stack Airbnb clone with modern UI and cloud image storage.',
    image: 'images/collage-airbnb.png',
    live: 'https://mmbnb.vercel.app',
  },
]; 